### PR TITLE
Clean up the student url scheme

### PR DESCRIPTION
**Pull request by SAMdroid-apps**
Remove the weird optimization hack from the
urls and use slashes for a nicer url!

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Ooops, I commited it on top of the reverted commit.  you can probably still do it :)

**Comment by ty221** [comment]
Sure I can do that and will do that in the second

**Comment by SAMdroid-apps** [comment]
Hi @ty221,
Why did you rebase this and change the commit message?  Commit messages are meant to be descriptive of the change, and "Merged pull request #9" is not.

**Comment by ty221** [comment]
I rebased it to because it was faster for me. Everybody can check what is pull request #9, by clicking a link. Messages shouldn't be longer than 40 chars also...

**Comment by SAMdroid-apps** [comment]
40 chars?  It is 80 mate.

**Comment by SAMdroid-apps** [comment]
@ty221 BTW:  you added "+" into the code and mucked up the merge.

**Pull request closed without merging**
