### PR TITLE
Added an update button

### PR DESCRIPTION
**Pull request by anurag-ks**

### CODE REVIEW

**Comment by ty221** [comment]
Hello! 
Thank you for your edit, however I'm not sure about two things:

a) ranking self-updates every 5 minutes; this button will give possibility to everybody to call update function - then, when there will be many similar requests, server might crash (this function downloads big files from 12 organizations)... Please consider that...

b) We've got update.sh script, it will be fine to call it instead of rewriting code, that's more secure

**Comment by ty221** [comment]
@ignaciouy Did you consider what I wrote?...

**Comment by SAMdroid-apps** [comment]
@ignaciouy I agree with @ty221.  Please don't use all your cpu or ram!  Please don't hog the network, the whole point of caching is to reduce network load!

Maybe we could just add a thing down the bottom that says "last updated ..., next update ..."?

BTW: I am the sysadmin hosting this

**Comment by ty221** [comment]
@ignaciouy @SAMdroid-apps I have reverted you merge-commit I'm sorry I had too. I tested this button it makes website loading incredibly long!

**Comment by ignaciouy** [comment]
I'm working on that..

**Comment by ty221** [comment]
@ignaciouy Ok, I pushed commit just now,

**Comment by anurag-ks** [comment]
I think that makes sense, I didn't kept that in mind and just wrote this
stuff. Sorry

anurag-ks-29

**Comment by ignaciouy** [comment]
@anurag-ks thanks for your patch anyway, maybe, you want to look how I use subprocess for dont freeze the leaderboard

**Comment by anurag-ks** [comment]
I was thinking if we could make the update specific to an org, and ..... the button on the /all/ will update for every org.

**Comment by SAMdroid-apps** [comment]
+1

**Pull request merged**
